spring:
  application:
    name: open-ai-demo
  ai:
    chat:
      client:
        enabled: false
    openai:
      api-key: "test-api-key"
      chat:
        base-url: http://localhost:12434/v1
        model: gemma3
    ollama:
      base-url: http://localhost:11434/v1
      chat:
        model: llama3.2:1b
      init:
        pull-model-strategy: when_missing

server:
  servlet:
    context-path: /open-ai-demo
